version: '3'
services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
        - MYSQL_ROOT_PASSWORD=tatapouet
        - MYSQL_DATABASE=tatapouet
        - MYSQL_USER=ben
        - MYSQL_PASSWORD=tatapouet
    volumes:
        - ./db:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
    - mysql-server:db
    ports:
    - 3333:80
