spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tatapouet
    username: ben
    password: tatapouet
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8889

oauth:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs9ctC+r7Kte2NwrXnXd+
    2C55yES3v9RWSm7ZMyjWCdne18/4POwtDvBUP/SXAgrf+lVOr3WMnJfg/TIeldXZ
    dtujsrNrS8UwtJrnlm8XSso1oYljkU9zA+Rvxfif1xTjs9ORIe9Oi45s/tqLCFe0
    4CMNLPKBsxhGdCwhqj/+CeSX72uaI0gI8u0WkqVzRzAbHrDqQu+wiVUaOAqW2hHL
    hqKZi5uD6wUUjLujlL3VLBc5eMMl/3hhtaDMgiEdFbbHEzWc200yVor7b5vPueog
    7IHHE9k2wPtjLubpmIoxLv8t+oq/LaHVoZfYahvsRDVIOJriudz/OnvhPf8KIPjG
    owIDAQAB
    -----END PUBLIC KEY-----
