spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tatapouet
    username: ben
    password: tatapouet
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 2222

